### ISSUE TITLE
Problem generating 2 wildcard certificates

### ISSUE THREAD

**Issue by carlos-alarcon** [ocelotconsulting/node-acme-lambda#26]
Hi I am trying to use your lambda to generate 2 wildcard certs:

Using the following setup (from local running npm run certs):
```
const defaultCertInfo = {
  'iontab': [ '*.iontab.es', 'iontab.es' ],
  'iontab-dev': [ '*.iontab-dev.es', 'iontab-dev.es' ]
};

const productionDirectoryUrl = process.env.ACME_DIRECTORY_URL || 'https://acme-v02.api.letsencrypt.org';
const stagingDirectoryUrl = process.env.ACME_DIRECTORY_URL || 'https://acme-staging-v02.api.letsencrypt.org';
```

1. First time it runs seems to generate 'acme-account-file' twice (overwriting it the second time it runs, I guess)
```
s3://acme-certs.iontab.dev/node-acme-lambda/iontab.json does not exist.
Certificate with key iontab is missing, going to regenerate.
s3://acme-certs.iontab.dev/node-acme-lambda/iontab-dev.json does not exist.
Certificate with key iontab-dev is missing, going to regenerate.
s3://acme-account.iontab.dev/node-acme-lambda/acme-account-file.json does not exist.
Creating user config file since couldn't read s3://acme-account.iontab.dev/node-acme-lambda/acme-account-file.json
Creating new account with url https://acme-staging-v02.api.letsencrypt.org/acme/new-acct
s3://acme-account.iontab.dev/node-acme-lambda/acme-account-file.json does not exist.
Creating user config file since couldn't read s3://acme-account.iontab.dev/node-acme-lambda/acme-account-file.json
Creating new account with url https://acme-staging-v02.api.letsencrypt.org/acme/new-acct
```

2. After generating account file (I think it is done twice, from logs). It creates the DNS challenges, create the CSR for both certificates and then raises an exception:
```
Attempt 13 to resolve TXT record for iontab-dev.es
Attempt 14 to resolve TXT record for iontab.es
deprecation notice: new signature for signJws(keypair, header, protect, payload)
deprecation notice: new signature for signJws(keypair, header, protect, payload)
Creating CSR for ["*.iontab-dev.es","iontab-dev.es"]
Requesting certificate.
deprecation notice: new signature for signJws(keypair, header, protect, payload)
deprecation notice: new signature for signJws(keypair, header, protect, payload)
deprecation notice: new signature for signJws(keypair, header, protect, payload)
Creating CSR for ["*.iontab.es","iontab.es"]
Requesting certificate.
deprecation notice: new signature for signJws(keypair, header, protect, payload)
Results are [{"err":true,"msg":"Updating cert for iontab, received err Error: Bad Request, Error: Bad Request\n    at Request.callback (/home/calarcon/ionide/server/node-acme-lambda/node_modules/superagent/lib/node/index.js:696:15)\n    at parser (/home/calarcon/ionide/server/node-acme-lambda/node_modules/superagent/lib/node/index.js:906:18)\n    at IncomingMessage.res.on (/home/calarcon/ionide/server/node-acme-lambda/node_modules/superagent/lib/node/parsers/json.js:19:7)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)"},{"err":true,"msg":"Updating cert for iontab-dev, received err Error: Bad Request, Error: Bad Request\n    at Request.callback (/home/calarcon/ionide/server/node-acme-lambda/node_modules/superagent/lib/node/index.js:696:15)\n    at parser (/home/calarcon/ionide/server/node-acme-lambda/node_modules/superagent/lib/node/index.js:906:18)\n    at IncomingMessage.res.on (/home/calarcon/ionide/server/node-acme-lambda/node_modules/superagent/lib/node/parsers/json.js:19:7)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)"}]
```

2. If I run the npm run local-cert It won't create the account info again (it was already created from previous run) but will still fail after generating the CSR (seems that it worked for on cert, the second, but failed for the first one)
```
Attempt 14 to resolve TXT record for iontab-dev.es
deprecation notice: new signature for signJws(keypair, header, protect, payload)
deprecation notice: new signature for signJws(keypair, header, protect, payload)
Creating CSR for ["*.iontab.es","iontab.es"]
Requesting certificate.
deprecation notice: new signature for signJws(keypair, header, protect, payload)
Attempt 15 to resolve TXT record for iontab-dev.es
Attempt 16 to resolve TXT record for iontab-dev.es
Attempt 17 to resolve TXT record for iontab-dev.es
Attempt 18 to resolve TXT record for iontab-dev.es
Attempt 19 to resolve TXT record for iontab-dev.es
Attempt 20 to resolve TXT record for iontab-dev.es
Attempt 21 to resolve TXT record for iontab-dev.es
Attempt 22 to resolve TXT record for iontab-dev.es
deprecation notice: new signature for signJws(keypair, header, protect, payload)
deprecation notice: new signature for signJws(keypair, header, protect, payload)
Creating CSR for ["*.iontab-dev.es","iontab-dev.es"]
Requesting certificate.
deprecation notice: new signature for signJws(keypair, header, protect, payload)
Results are [{"err":true,"msg":"Updating cert for iontab, received err Error: Bad Request, Error: Bad Request\n    at Request.callback (/home/calarcon/ionide/server/node-acme-lambda/node_modules/superagent/lib/node/index.js:696:15)\n    at parser (/home/calarcon/ionide/server/node-acme-lambda/node_modules/superagent/lib/node/index.js:906:18)\n    at IncomingMessage.res.on (/home/calarcon/ionide/server/node-acme-lambda/node_modules/superagent/lib/node/parsers/json.js:19:7)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)"},{"ETag":"\"3e4fcac0ac004bdba1a54be556fae9fd\""}]
```
Maybe it is due because I already had a cert for the first domain (I deleted both S3 buckets before testing with 2 domains at once, which I do not know if is the proper way of doing, if not I would thank any indication about how to do it. I am working with staging v2 right now)

Any clue on whats going on?

Beside that, I would love the feature of leaving pem files in S3 bucket: #18.

Regards

**Comment by carlos-alarcon** [comment]
Seems that after running it several times (failing each of those times) it finally gets working:
```
Attempt 20 to resolve TXT record for iontab.es
deprecation notice: new signature for signJws(keypair, header, protect, payload)
deprecation notice: new signature for signJws(keypair, header, protect, payload)
Creating CSR for ["*.iontab.es","iontab.es"]
Requesting certificate.
deprecation notice: new signature for signJws(keypair, header, protect, payload)
Results are [{"ETag":"\"64a2ff2b01ddfba5b8a664a51eb543b7\""},{"err":false,"msg":"Certificate for iontab-dev is still valid, going back to bed."}]

```

**Comment by larryboymi** [comment]
There's a chance there are issues with the LE servers (I experienced them a lot as they were moving to v2). Let me know if you continue to encounter 400's.
